version: 3

project:
  locator: SolaceProducts_terraform-provider-solacebrokerappliance
  id: SolaceProducts_terraform-provider-solacebrokerappliance
  name: terraform-provider-solacebrokerappliance
  teams: []
  labels:
    - go

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
