name: Test Provider

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & test Terraform provider
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: "1.25"

      - name: Check out code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Terraform latest
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
        with:
          terraform_wrapper: false

      - name: Build provider
        run: |
          make install
          ~/go/bin/terraform-provider-solacebrokerappliance version
          ~/go/bin/terraform-provider-solacebrokerappliance help

  Plugin-Integration-Test:
    needs: build
    uses: ./.github/workflows/provider-test-pipeline.yml
    secrets: inherit

  Plugin-Acceptance-Test:
    needs: build
    uses: ./.github/workflows/provider-acceptance-test.yml
    secrets: inherit

  CLI-Integration-Test:
    needs: build
    uses: ./.github/workflows/cli-test-pipeline.yml
    secrets: inherit